version: '3.8'

services:
  # DDNS-GO - 动态域名解析
  ddns-go:
    image: jeessy/ddns-go
    container_name: ddns-go
    restart: unless-stopped
    ports:
      - "9876:9876"
    environment:
      - DDNS_GO_IPV4=1
      - DDNS_GO_DDNS_LIST=example.com
      - DDNS_GO_INTERVAL=600
      - DDNS_GO_PROXY_MODE=1
    volumes:
      - ./ddns:/etc/ddns