version: '3.8'

services:
  # Music Tag - 音乐标签管理
  music-tag:
    image: xhongc/music_tag_web:latest
    container_name: music-tag-web
    restart: unless-stopped
    ports:
      - "8002:8002"
    volumes:
      - /volume1/music:/app/media:rw
      - ./config:/app/data