version: '3.8'

services:
  # V2rayA - 代理工具
  v2raya:
    image: mzz2017/v2raya:latest
    container_name: v2raya
    restart: always
    network_mode: host
    privileged: true
    environment:
      - V2RAYA_CONFIG:/etc/v2raya
      - V2RAYA_ADDRESS=0.0.0.0:2017
      - V2RAYA_PLUGINLISTENPORT:32346
      - V2RAYA_V2RAY_BIN=/usr/local/bin/xray
    volumes:
      - ./data:/etc/v2raya
      - /lib/modules:/lib/modules:ro
      - /etc/resolv.conf:/etc/resolv.conf
    labels:
      createdBy: "Apps"