version: '3.8'

services:
  # Sync Clipboard - 剪贴板同步服务
  syncclipboard-server:
    image: jericx/syncclipboard-server:latest
    container_name: syncclipboard
    restart: always
    networks:
      - 1panel-network
    ports:
      - "5033:5033"
    volumes:
      - ./data/appsettings.json:/app/appsettings.json
    labels:
      createdBy: "Apps"

networks:
  1panel-network:
    external: true