version: '3.8'

services:
  # Docker Copilot - Docker 管理工具
  dockercopilot:
    image: 0nlylty/dockercopilot:latest
    container_name: dockerCopilot
    restart: always
    privileged: true
    ports:
      - 12712:12712
    environment:
      - TZ=Asia/Shanghai
      - secretKey=TOKEN
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/data